//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Account
{
	public virtual string Email
	{
		get;
		set;
	}

	public virtual string Password
	{
		get;
		set;
	}

	public virtual string Type
	{
		get;
		set;
	}

	public virtual string Id
	{
		get;
		set;
	}

	public virtual string PersonId
	{
		get;
		set;
	}

}

