//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Cook : Person
{
	public virtual string TravelCapabilities
	{
		get;
		set;
	}

	public virtual object PvgStatus
	{
		get;
		set;
	}

	public virtual object FoodHygieneStatus
	{
		get;
		set;
	}

	public virtual string FoodPreferences
	{
		get;
		set;
	}

}

