//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Person
{
	public virtual string FirstName
	{
		get;
		set;
	}

	public virtual string Surname
	{
		get;
		set;
	}

	public virtual string PhoneNumber
	{
		get;
		set;
	}

	public virtual Address Address
	{
		get;
		set;
	}

	public virtual string Id
	{
		get;
		set;
	}

}

